CREATE DATABASE burger_db;

USE burger_db;

CREATE TABLE burgers (
	id INT AUTO_INCREMENT NOT NULL,
	burger varchar(255) NOT NULL,
    devour BOOLEAN DEFAULT false,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id)
);

